/**
 * This module exports Action names
 * @module Speed/ActionTypes
 */

export const FETCH_ALL_LOCATIONS_SPEED_REQUEST = 'SPEED/FETCH_ALL_LOCATIONS_SPEED_REQUEST';

export const FETCH_ALL_LOCATIONS_SPEED_SUCCEED = 'SPEED/FETCH_ALL_LOCATIONS_SPEED_SUCCEED';

export const FETCH_ALL_LOCATIONS_SPEED_FAILURE = 'SPEED/FETCH_ALL_LOCATIONS_SPEED_FAILURE';

export const ZOOM_END = 'SPEED/ZOOM_END';
